# -*- coding: utf-8 -*-
"""praktikum4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Sabrinabhinaa/7c1669229a7a18a1c2887fabfffec050/praktikum4.ipynb

**Praktikum 4**

**Kelompok 12**

*   Sabrina Ramadhani - 0110222068
*   Disitia Fajar Familiati - 0110222163
*   M. Faris Zacky - 0110222227

**Basic Bar Chart**
"""

import matplotlib.pyplot as plt

# Data
jurusan = ['Ilmu Komputer', 'Sistem Informasi', 'Teknik Informatika', 'Data Science']
jumlah_mahasiswa = [120, 150, 100, 80]

# Membuat Basic Bar Chart
plt.bar(jurusan, jumlah_mahasiswa)
plt.title('Jumlah Mahasiswa per Jurusan')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.show()

"""**Basic Bar Chart dengan Matplotlib**"""

import matplotlib.pyplot as plt

# Data
jurusan = ['Ilmu Komputer', 'Sistem Informasi', 'Teknik Informatika', 'Data Science']
jumlah_mahasiswa = [120, 150, 100, 80]

# Bar Chart
plt.bar(jurusan, jumlah_mahasiswa, color='skyblue')
plt.title('Jumlah Mahasiswa per Jurusan')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)  # Menambahkan grid horizontal
plt.show()

"""**Kustomisasi Basic Bar Chart**"""

import matplotlib.pyplot as plt

# Data
jurusan = ['Ilmu Komputer', 'Sistem Informasi', 'Teknik Informatika', 'Data Science']
jumlah_mahasiswa = [120, 150, 100, 80]

# Menambahkan kustomisasi
colors = ['blue', 'green', 'red', 'purple']
plt.bar(jurusan, jumlah_mahasiswa, color=colors)
plt.title('Jumlah Mahasiswa per Jurusan')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)

# Menambahkan label angka di atas bar
for i, v in enumerate(jumlah_mahasiswa):
    plt.text(i, v + 5, str(v), ha='center')
plt.show()

"""**Multiple Bar Chart**"""

import matplotlib.pyplot as plt

# Data
jurusan = ['Ilmu Komputer', 'Sistem Informasi', 'Teknik Informatika', 'Data Science']
jumlah_mahasiswa = [120, 150, 100, 30]

# Data tahun 2024
jumlah_mahasiswa_2024 = [110, 140, 95, 85]

x = range(len(jurusan))  # Indeks posisi untuk batang
width = 0.4

plt.bar(x, jumlah_mahasiswa, width=width, label='2023', color='skyblue')
plt.bar([p + width for p in x], jumlah_mahasiswa_2024, width=width, label='2024', color='orange')

plt.title('Jumlah Mahasiswa per Jurusan (2023 vs 2024)')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks([p + width/2 for p in x], jurusan, rotation=45)
plt.legend()
plt.show()

"""**Pola dan Tren dengan Bar Chart**"""

import matplotlib.pyplot as plt

# Data jumlah mahasiswa per tahun
jurusan = ['Ilmu Komputer', 'Sistem Informasi', 'Teknik Informatika', 'Data Science']
tahun = ['2019', '2020', '2021', '2022', '2023']
data = {
    'Ilmu Komputer': [100, 110, 120, 130, 140],
    'Sistem Informasi': [120, 125, 135, 145, 160],
    'Teknik Informatika': [90, 95, 100, 105, 110],
    'Data Science': [70, 75, 80, 85, 90]
}

# Lebar bar
width = 0.2
x = range(len(tahun))

# Visualisasi untuk masing-masing jurusan
plt.bar([p - width*1.5 for p in x], data['Ilmu Komputer'], width=width, label='Ilmu Komputer', color='blue')
plt.bar([p - width*0.5 for p in x], data['Sistem Informasi'], width=width, label='Sistem Informasi', color='green')
plt.bar([p + width*0.5 for p in x], data['Teknik Informatika'], width=width, label='Teknik Informatika', color='orange')
plt.bar([p + width*1.5 for p in x], data['Data Science'], width=width, label='Data Science', color='purple')

# Memberikan detail pada grafik
plt.title('Tren Jumlah Mahasiswa per Jurusan (2019–2023)')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(x, tahun)
plt.legend()

# Menampilkan grafik
plt.show()